Numarataj.WebUI/Areas/Admin/Controllers/PdfController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Numarataj.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using iTextSharp.text.pdf;
using iTextSharp.text;
using Numarataj.DTO.DTOs.BasePdfDTOs;

namespace Numarataj.WebUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,Personel")]
    [Area("Admin")]
    public class PdfController : Controller
    {
        private readonly NumaratajDbContext _context;
        private readonly IMapper _mapper;

        public PdfController(NumaratajDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        public async Task<IActionResult> GeneratePdf(int id, string title, string pdfName, int type, bool isTcHidden = false)
        {
            var ozelisyeriValues = await _context.OzelIsyeri.FirstOrDefaultAsync(x => x.BelgeNoId == id);
            var adresTespitResponse = _mapper.Map<ResultPdfDto>(ozelisyeriValues);

            if (type == 1)
            {
                var adresTespitValues = await _context.AdresTespit.FirstOrDefaultAsync(x => x.BelgeNoId == id);
                adresTespitResponse = _mapper.Map<ResultPdfDto>(adresTespitValues);
            }
            if (type == 2)
            {
                ozelisyeriValues = await _context.OzelIsyeri.FirstOrDefaultAsync(x => x.BelgeNoId == id);
                adresTespitResponse = _mapper.Map<ResultPdfDto>(ozelisyeriValues);
            }
            if (type == 3)
            {
                var sahacalismasiValues = await _context.SahaCalismasi.FirstOrDefaultAsync(x => x.BelgeNoId == id);
                adresTespitResponse = _mapper.Map<ResultPdfDto>(sahacalismasiValues);
            }
            if (type == 4)
            {
                var resmikurumValues = await _context.ResmiKurum.FirstOrDefaultAsync(x => x.BelgeNoId == id);
                adresTespitResponse = _mapper.Map<ResultPdfDto>(resmikurumValues);
            }
            if (type == 5)
            {
                var yenibinaValues = await _context.YeniBina.FirstOrDefaultAsync(x => x.BelgeNoId == id);
                adresTespitResponse = _mapper.Map<ResultPdfDto>(yenibinaValues);
            }
            //var adresTespitResponse = await _client.GetFromJsonAsync<ResultPdfDto>($"ozelisyeris/{id}");
            if (adresTespitResponse == null)
            {
                return NotFound(); // Eğer veri yoksa 404 döndür
            }

            using (MemoryStream stream = new MemoryStream())
            {
                // PDF belgesi oluşturma
                Document pdfDoc = new Document(PageSize.A4, 50, 50, 25, 25);
                PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
                pdfDoc.Open();

                // Türkçe karakterler için Arial Unicode MS fontunu kullanıyoruz
                string arialUnicodeMSPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Fonts), "ARIALUNI.TTF");
                BaseFont bfArialUniCode = BaseFont.CreateFont(arialUnicodeMSPath, BaseFont.IDENTITY_H, BaseFont.EMBEDDED);

                // Font ayarları
                Font titleFont = new Font(bfArialUniCode, 16, Font.BOLD);
                Font headerFont = new Font(bfArialUniCode, 12, Font.BOLD);
                Font bodyFont = new Font(bfArialUniCode, 10, Font.NORMAL);
                Font kalinFont = new Font(bfArialUniCode, 20, Font.BOLD);

                // ** Logo Ekleyin (Sol Üst Kısım) **
                var logoPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/matrix-admin-master/assets/images/logo-rapor.png");
                //string logoPath = @"C:\Users\IRMAKTEKNOLOJI\source\repos\Numarataj\Numarataj.WebUI\wwwroot\matrix-admin-master\assets\images\logo-rapor.png";
                iTextSharp.text.Image logo = iTextSharp.text.Image.GetInstance(logoPath);

                // Logonun boyutunu ayarlayın (çok büyük olmaması için)
                logo.ScaleToFit(110f, 60f); // Genişlik 100, yükseklik 50 olacak şekilde ayarlandı
                logo.SetAbsolutePosition(43, pdfDoc.PageSize.Height - 100); // Sol üst köşeye, hafif aşağıda
                pdfDoc.Add(logo);

                // Belge Başlıkları
                var tCParagraph = new Paragraph(new Chunk("T.C.", titleFont)) { Alignment = Element.ALIGN_CENTER };
                pdfDoc.Add(tCParagraph);

                var belediyeBaskamligiParagraph = new Paragraph(new Chunk("BATMAN BELEDİYE BAŞKANLIĞI", titleFont)) { Alignment = Element.ALIGN_CENTER };
                pdfDoc.Add(belediyeBaskamligiParagraph);

                var imarMudurluguParagraph = new Paragraph(new Chunk("İMAR VE ŞEHİRCİLİK MÜDÜRLÜĞÜ", headerFont)) { Alignment = Element.ALIGN_CENTER };
                pdfDoc.Add(imarMudurluguParagraph);

                var etutProjeParagraph = new Paragraph(new Chunk("NUMARATAJ BİRİMİ", bodyFont)) { Alignment = Element.ALIGN_CENTER };
                pdfDoc.Add(etutProjeParagraph);
                pdfDoc.Add(new Paragraph("\n"));
                pdfDoc.Add(new Paragraph("\n"));



                PdfPTable numaratajTable = new PdfPTable(3);
                numaratajTable.WidthPercentage = 100;
                numaratajTable.SetWidths(new float[] { 1, 3, 1 }); // İlk ve son sütun dar, orta sütun geniş

                // "Belge No" hücresini sola hizala
                numaratajTable.AddCell(new PdfPCell(new Phrase("Belge No: " + (adresTespitResponse.BelgeNoId.ToString() ?? ""), bodyFont))
                {
                    Border = Rectangle.NO_BORDER, // Kenar çizgisi yok
                    HorizontalAlignment = Element.ALIGN_LEFT // Sol hizalama
                });

                // "NUMARATAJ BELGESİ" hücresini ortala
                numaratajTable.AddCell(new PdfPCell(new Phrase("NUMARATAJ BELGESİ", kalinFont))
                {
                    Border = Rectangle.NO_BORDER, // Kenar çizgisi yok
                    HorizontalAlignment = Element.ALIGN_CENTER // Ortala
                });

                // "Tarih" hücresini sağa hizala
                numaratajTable.AddCell(new PdfPCell(new Phrase(DateTime.Now.ToString("dd/MM/yyyy"), bodyFont))
                {
                    Border = Rectangle.NO_BORDER, // Kenar çizgisi yok
                    HorizontalAlignment = Element.ALIGN_RIGHT // Sağ hizalama
                });

                // Tabloyu PDF belgesine ekle
                pdfDoc.Add(numaratajTable);

                // Boşluk ekle
                pdfDoc.Add(new Paragraph("\n"));



                PdfPTable specialBusinessTable = new PdfPTable(1)
                {
                    WidthPercentage = 100
                };

                // Kenar çizgilerini eklemek için hücre oluştur
                PdfPCell specialBusinessCell = new PdfPCell(new Phrase(title, titleFont))
                {
                    HorizontalAlignment = Element.ALIGN_CENTER, // Ortala
                    Border = Rectangle.BOX, // Kenar çizgisi ekle
                    Padding = 10 // Hücre içindeki boşluk
                };
                specialBusinessCell.BorderWidth = 2; // Kenar kalınlığını ayarla
                specialBusinessTable.AddCell(specialBusinessCell);

                // Tabloyu PDF belgesine ekle
                pdfDoc.Add(specialBusinessTable);

                var headerParagraph = new Paragraph("KİMLİK BİLGİLERİ", headerFont);
                headerParagraph.SpacingAfter = 5f; // 5 birim boşluk bırakıyoruz
                pdfDoc.Add(headerParagraph);

                // Kimlik bilgileri tablosu
                PdfPTable kimlikTable = new PdfPTable(2);
                kimlikTable.WidthPercentage = 100;
                if (!isTcHidden)
                {
                    kimlikTable.AddCell(new PdfPCell(new Phrase("TC Kimlik No:", bodyFont)) { Padding = 8, MinimumHeight = 8 });
                    kimlikTable.AddCell(new PdfPCell(new Phrase(adresTespitResponse.TcKimlikNo, bodyFont)) { Padding = 8, MinimumHeight = 8 });
                }
                kimlikTable.AddCell(new PdfPCell(new Phrase("Ad/Soyad:", bodyFont)) { Padding = 8, MinimumHeight = 8 });
                kimlikTable.AddCell(new PdfPCell(new Phrase(adresTespitResponse.AdSoyad, bodyFont)) { Padding = 8, MinimumHeight = 8 });
                kimlikTable.AddCell(new PdfPCell(new Phrase("Telefon:", bodyFont)) { Padding = 8, MinimumHeight = 8 });
                kimlikTable.AddCell(new PdfPCell(new Phrase(adresTespitResponse.Telefon ?? "", bodyFont)) { Padding = 8, MinimumHeight = 8 });

                pdfDoc.Add(kimlikTable);

                var adresHeaderParagraph = new Paragraph("ADRES BİLGİLERİ", headerFont);
                adresHeaderParagraph.SpacingAfter = 5f; // 5 birim boşluk bırakıyoruz
                pdfDoc.Add(adresHeaderParagraph);

                PdfPTable adresTable = new PdfPTable(2);
                adresTable.WidthPercentage = 100;

                adresTable.AddCell(new PdfPCell(new Phrase("Adres No:", bodyFont)) { Padding = 8, MinimumHeight = 8 });
                adresTable.AddCell(new PdfPCell(new Phrase(adresTespitResponse.AdresNo?.ToString() ?? "", bodyFont)) { Padding = 8, MinimumHeight = 8 });
                adresTable.AddCell(new PdfPCell(new Phrase("Mahalle:", bodyFont)) { Padding = 8, MinimumHeight = 8 });
                adresTable.AddCell(new PdfPCell(new Phrase(adresTespitResponse.Mahalle ?? "", bodyFont)) { Padding = 8, MinimumHeight = 8 });
                adresTable.AddCell(new PdfPCell(new Phrase("Cadde/Sokak:", bodyFont)) { Padding = 8, MinimumHeight = 8 });
                adresTable.AddCell(new PdfPCell(new Phrase(adresTespitResponse.CaddeSokak ?? "", bodyFont)) { Padding = 8, MinimumHeight = 8 });
                adresTable.AddCell(new PdfPCell(new Phrase("Dış Kapı:", bodyFont)) { Padding = 8, MinimumHeight = 8 });

Numarataj.WebUI/Areas/Admin/Controllers/YeniBinaController.cs
using Microsoft.AspNetCore.Mvc;
using Numarataj.WebUI.Helpers;
using Microsoft.AspNetCore.Authorization;
using Numarataj.DTO.DTOs.YeniBinaDtos;
using AutoMapper;
using Numarataj.DataAccess.Context;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Numarataj.Entity.Entities;

namespace Numarataj.WebUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,Personel")]
    [Area("Admin")]
    public class YeniBinaController : Controller
    {
        private readonly NumaratajDbContext _context;
        private readonly IMapper _mapper;

        public YeniBinaController(NumaratajDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }
        [HttpGet]
        [Route("YeniBina/index")]
        public async Task<IActionResult> Index()
        {
            var values = await _context.YeniBina.ToListAsync();
            var resultDtos = _mapper.Map<List<ResultYeniBinaDto>>(values);
            return View(resultDtos);
        }
        [HttpGet]
        [Route("YeniBina/Create")]
        public IActionResult CreateYeniBina()
        {
            ViewBag.Mahalleler = Constants.Mahalleler;
            return View();
        }

        [HttpPost]
        [Route("YeniBina/Create")]
        public async Task<IActionResult> CreateYeniBina(CreateYeniBinaDto createYeniBinaDto)
        {
            if (!ModelState.IsValid)
            {
                return View(createYeniBinaDto);
            }

            var yeniBina = _mapper.Map<YeniBina>(createYeniBinaDto);
            await _context.YeniBina.AddAsync(yeniBina);
            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] = "Yeni Bina Alanı Oluşturuldu";
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> UpdateYeniBina(int belgeNoId)
        {
            var yeniBina = await _context.YeniBina.FirstOrDefaultAsync(x => x.BelgeNoId == belgeNoId);
            if (yeniBina == null)
            {
                return NotFound();
            }

            var updateYeniBinaDto = _mapper.Map<UpdateYeniBinaDto>(yeniBina);
            ViewBag.MahalleListesi = Constants.Mahalleler.Select(m => new SelectListItem
            {
                Text = m,
                Value = m,
                Selected = m == updateYeniBinaDto.Mahalle
            }).ToList();

            return View("UpdateYeniBina", updateYeniBinaDto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateYeniBina(UpdateYeniBinaDto updateYeniBinaDto)
        {
            if (ModelState.IsValid)
            {
                var yeniBina = await _context.YeniBina.FirstOrDefaultAsync(x => x.BelgeNoId == updateYeniBinaDto.BelgeNoId);
                if (yeniBina == null)
                {
                    return NotFound();
                }

                _mapper.Map(updateYeniBinaDto, yeniBina);
                _context.YeniBina.Update(yeniBina);
                await _context.SaveChangesAsync();

                TempData["SuccessMessage"] = "Güncelleme işlemi başarılı!";
                return RedirectToAction("Index");
            }

            ViewBag.Mahalleler = Constants.Mahalleler;
            return View(updateYeniBinaDto);
        }


        [HttpPost]
        [Route("YeniBina/Delete/{id:int}")]
        public async Task<IActionResult> DeleteYeniBina(int id)
        {
            var yeniBina = await _context.YeniBina.FindAsync(id);
            if (yeniBina == null)
            {
                return NotFound();
            }

            _context.YeniBina.Remove(yeniBina);
            await _context.SaveChangesAsync();
            TempData["SuccessMessage"] = "Yeni Bina başarıyla silindi";
            return RedirectToAction(nameof(Index));
        }

    }
}

Numarataj.WebUI/Areas/Admin/Views/YeniBina/Index.cshtml
@model List<ResultYeniBinaDto>

@{
    ViewData["Title"] = "YENİ BİNA SAYFASI";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- DataTables CSS -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

<style>
    .btn-outline-danger {
        background-color: #d9534f;
        color: white;
    }

    .btn-outline-info {
        background-color: #5bc0de;
        color: white;
    }

    .btn-outline-primary {
        background-color: #0275d8;
        color: white;
    }

    .btn-outline-success {
        background-color: #5cb85c;
        color: white;
    }

    #yeniBinaTable tbody tr:hover > td {
        background-color: #91c6ff !important;
    }

    .container {
        max-width: 100%;
        margin: 0;
        padding: 0;
    }

    table.dataTable {
        margin: 0;
    }

    .btn-group .btn {
        margin-right: 5px;
    }

    .btn-group {
        display: flex;
        gap: 5px;
    }

    .alert-container {
        margin-top: 10px;
    }

    .top-button-container {
        display: flex;
        position: relative; /* Konumlandırmayı göreli yapar */
        justify-content: flex-end;
        margin-bottom: 10px;
    }

        .top-button-container a {
            position: absolute;
            top: 5px; /* Butonu aşağı kaydırır */
            right: 0;
            z-index: 10; /* Butonu öne getirir */
        }
</style>

@if (TempData["SuccessMessage"] != null)
{
    <div id="successMessage" class="alert alert-success" role="alert">
        @TempData["SuccessMessage"]
    </div>
}

<div class="container mt-2">
    <div class="top-button-container">
        <a asp-area="Admin" asp-controller="YeniBina" asp-action="CreateYeniBina" class="btn btn-outline-primary">Yeni Bina Ekle</a>
    </div>
    <table id="yeniBinaTable" class="display table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>B.No</th>
                <th>TC</th>
                <th>Ad Soyad</th>
                <th>Tarih</th>
                <th>Telefon</th>
                <th>Mahalle</th>
                <th>Sokak</th>
                <th>DışKapı</th>
                <th>İşlem</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.BelgeNoId</td>
                    <td class="tc-kimlik">
                        <span class="tc-value">@item.TcKimlikNo</span>
                        <input type="checkbox" class="hide-tc-checkbox" />
                    </td>

                    <td>@item.AdSoyad</td>
                    <td>@item.Tarih</td>
                    <td>@item.Telefon</td>
                    <td>@item.Mahalle</td>
                    <td>@item.CaddeSokak</td>
                    <td>@item.DisKapi</td>
                    <td>
                        <div class="btn-group">
                            <button class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#deleteModal-@item.BelgeNoId">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                            <a asp-area="Admin" asp-controller="YeniBina" asp-action="UpdateYeniBina" asp-route-belgeNoId="@item.BelgeNoId" class="btn btn-sm btn-outline-success">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="@Url.Action("GeneratePdf", "Pdf", new { area = "Admin", id = item.BelgeNoId, title = "YENİ BİNA", pdfName = "YeniBinaRaporu.pdf", type = 5 })"
                               class="btn btn-sm btn-outline-info yeni-bina-pdf-button"
                               data-id="@item.BelgeNoId">
                                <i class="fas fa-file-pdf"></i> PDF
                            </a>

                        </div>
                    </td>
                </tr>

                <!-- Modal Structure for Delete Confirmation -->
                <div class="modal fade" id="deleteModal-@item.BelgeNoId" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel-@item.BelgeNoId" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header bg-danger text-white">
                                <h5 class="modal-title" id="deleteModalLabel-@item.BelgeNoId">Silme Onayı</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Bu kaydı silmek istediğinize emin misiniz?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Vazgeç</button>
                                <form asp-action="DeleteYeniBina" asp-controller="YeniBina" asp-area="Admin" asp-route-id="@item.BelgeNoId" method="post" style="display:inline;">
                                    <button type="submit" class="btn btn-danger">Onayla</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </tbody>
    </table>
</div>

<script>
    function toggleTcVisibility(checkbox) {
        var tcValue = checkbox.closest('td').querySelector('.tc-value');
        if (checkbox.checked) {
            tcValue.style.display = 'none';
        } else {
            tcValue.style.display = 'inline';
        }
    }

    document.querySelectorAll('.hide-tc-checkbox').forEach(checkbox => {
        checkbox.addEventListener('change', function () {
            toggleTcVisibility(this);

            const row = this.closest('tr');
            const pdfButton = row.querySelector('.yeni-bina-pdf-button');
            const id = pdfButton.getAttribute('data-id');
            const isTcHidden = this.checked;

            // Yeni URL'yi isTcHidden parametresi ile oluştur
            pdfButton.href = `@Url.Action("GeneratePdf", "Pdf", new { area = "Admin" })?id=${id}&title=YENİ BİNA&pdfName=YeniBinaRaporu.pdf&type=5&isTcHidden=${isTcHidden}`;
        });
    });
    setTimeout(function () {
        var successMessage = document.getElementById("successMessage");
        if (successMessage) {
            successMessage.style.display = "none";
        }
    }, 2000);
</script>

Numarataj.WebUI/Areas/Admin/Views/YeniBina/UpdateYeniBina.cshtml
@model UpdateYeniBinaDto

@{
    ViewData["Title"] = "Yeni Bina Güncelleme Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-..." crossorigin="anonymous"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<style>
    .custom-form-container {
        background-color: #e6e0f8; /* Açık mor renk */
        padding: 20px; /* Formun çevresine dolgu */
        border-radius: 8px; /* Kenarları yuvarlatmak için */
        max-width: 1000px; /* Daha geniş bir maksimum genişlik */
        width: 90%; /* Tam ekran genişliğinin %90'ı */
        margin: auto;
    }
</style>

<form id="yeniBinaForm" method="post" asp-area="Admin" asp-controller="YeniBina" asp-action="UpdateYeniBina" class="custom-form-container">
    <input type="hidden" name="BelgeNoId" value="@Model.BelgeNoId" />
    @Html.AntiForgeryToken()
    <table class="table table-bordered">
        <tbody>
            <tr>
                <td>
                    <label for="TcKimlikNo" class="form-label">TC Kimlik No</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-id-card"></i></span>
                        </div>
                        <input type="text" class="form-control" id="TcKimlikNo" name="TcKimlikNo" placeholder="TC Kimlik No" maxlength="11" value="@Model.TcKimlikNo">
                    </div>
                </td>
                <td>
                    <label for="AdSoyad" class="form-label">Adı Soyadı</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" class="form-control" id="AdSoyad" name="AdSoyad" placeholder="Adı Soyadı" value="@Model.AdSoyad">
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="Telefon" class="form-label">Telefon</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-phone"></i></span>
                        </div>
                        <input type="text" class="form-control" id="Telefon" name="Telefon" placeholder="Telefon" value="@Model.Telefon">
                    </div>
                </td>
                <td>
                    <label for="inputMahalle" class="form-label">Mahalle</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-map-marker-alt"></i></span>
                        </div>
                        @Html.DropDownListFor(model => model.Mahalle,
                                 (IEnumerable<SelectListItem>)ViewBag.MahalleListesi,
                                 "Mahalle Seçiniz...",
                                 new { @class = "form-control", id = "inputMahalle" })
                    </div>
                </td>

            </tr>
            <tr>
                <td>
                    <label for="CaddeSokak" class="form-label">Cadde/Sokak</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-road"></i></span>
                        </div>
                        <input type="text" class="form-control" id="CaddeSokak" name="CaddeSokak" placeholder="Cadde/Sokak" value="@Model.CaddeSokak">
                    </div>
                </td>
                <td>
                    <label for="DisKapi" class="form-label">Dış Kapı</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-door-open"></i></span>
                        </div>
                        <input type="text" class="form-control" id="DisKapi" name="DisKapi" placeholder="Dış Kapı" value="@Model.DisKapi">
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="Ada" class="form-label">Ada</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-map"></i></span>
                        </div>
                        <input type="text" class="form-control" id="Ada" name="Ada" placeholder="Ada" value="@Model.Ada">
                    </div>
                </td>
                <td>
                    <label for="Parsel" class="form-label">Parsel</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-map"></i></span>
                        </div>
                        <input type="text" class="form-control" id="Parsel" name="Parsel" placeholder="Parsel" value="@Model.Parsel">
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2" class="text-center">
                    <input type="hidden" id="Tarih" name="Tarih" value="@Model.Tarih" />
                    <button type="submit" class="btn btn-primary">Güncelle</button>
                </td>
            </tr>
        </tbody>
    </table>
</form>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const tarihField = document.getElementById('Tarih');
        tarihField.value = new Date().toISOString().substring(0, 16);
    });
</script>